DesafioFortes.MVC/Controllers/DespesaController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using AutoMapper;
using DesafioFortes.Application.Interface;
using DesafioFortes.Domain.Entities;
using DesafioFortes.MVC.ViewModels;

namespace DesafioFortes.MVC.Controllers
{
    public class DespesaController : Controller
    {
        private readonly IDespesaAppService _despesaApp;
        private readonly ICategoriaAppService _categoriaApp;

        public DespesaController(IDespesaAppService despesaApp, ICategoriaAppService categoriaApp)
        {
            _despesaApp = despesaApp;
            _categoriaApp = categoriaApp;
        }
        //
        // GET: /Despesa/
        public ActionResult Index()
        {
            ViewBag.Categorias = new SelectList(_categoriaApp.GetAll(), "CategoriaId", "Nome");
            var despesaViewModel = Mapper.Map<IEnumerable<Despesa>, IEnumerable<DespesaViewModel>>(_despesaApp.GetAll());
            return View(despesaViewModel);
        }

        [HttpPost]
        public ViewResult Index(int? id)
        {
            ViewBag.Categorias = new SelectList(_categoriaApp.GetAll(), "CategoriaId", "Nome");
            var despesaViewModel = Mapper.Map<IEnumerable<Despesa>, IEnumerable<DespesaViewModel>>(id != null ? _categoriaApp.FiltrarDespesasPorCategoria(id) : _despesaApp.GetAll());
            return View(despesaViewModel);
        }


        //
        // GET: /Despesa/Details/5
        public ActionResult Details(int id)
        {
            var despesa = _despesaApp.GetById(id);
            var despesaViewModel = Mapper.Map<Despesa, DespesaViewModel>(despesa);
            return View(despesaViewModel);
        }

        //
        // GET: /Despesa/Create
        public ActionResult Create()
        {
            ViewBag.Categorias = new SelectList(_categoriaApp.GetAll(), "CategoriaId", "Nome");
            return View();
        }

        //
        // POST: /Despesa/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DespesaViewModel despesa)
        {
            if (ModelState.IsValid)
            {
                var despesaDomain = Mapper.Map<DespesaViewModel, Despesa>(despesa);
                _despesaApp.Add(despesaDomain);
                return RedirectToAction("Index");
            }

            ViewBag.Categorias = new SelectList(_categoriaApp.GetAll(), "CategoriaId", "Nome", despesa.CategoriaId);
            return View(despesa);
        }

        //
        // GET: /Despesa/Edit/5
        public ActionResult Edit(int id)
        {
            var despesa = _despesaApp.GetById(id);
            var despesaViewModel = Mapper.Map<Despesa, DespesaViewModel>(despesa);
            ViewBag.Categorias = new SelectList(_categoriaApp.GetAll(), "CategoriaId", "Nome", despesaViewModel.CategoriaId);
            return View(despesaViewModel);
        }

        //
        // POST: /Despesa/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DespesaViewModel despesa)
        {
            if (ModelState.IsValid)
            {
                var despesaDomain = Mapper.Map<DespesaViewModel, Despesa>(despesa);
                _despesaApp.Update(despesaDomain);
                return RedirectToAction("Index");
            }
            ViewBag.Categorias = new SelectList(_categoriaApp.GetAll(), "CategoriaId", "Nome", despesa.CategoriaId);
            return View(despesa);
        }

        //
        // GET: /Despesa/Delete/5
        public ActionResult Delete(int id)
        {
            var despesa = _despesaApp.GetById(id);
            var despesaViewModel = Mapper.Map<Despesa, DespesaViewModel>(despesa);
            return View(despesaViewModel);
        }

        //
        // POST: /Despesa/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var despesa = _despesaApp.GetById(id);
            _despesaApp.Remove(despesa);
            return RedirectToAction("Index");
        }
    }
}

DesafioFortes.MVC/Controllers/ReceitaController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using AutoMapper;
using DesafioFortes.Application.Interface;
using DesafioFortes.Domain.Entities;
using DesafioFortes.MVC.ViewModels;

namespace DesafioFortes.MVC.Controllers
{
    public class ReceitaController : Controller
    {
        private readonly IReceitaAppService _receitaApp;
        private readonly ICategoriaAppService _categoriaApp;

        public ReceitaController(IReceitaAppService receitaApp, ICategoriaAppService categoriaApp)
        {
            _receitaApp = receitaApp;
            _categoriaApp = categoriaApp;
        }

        //
        // GET: /Receitas/
        public ActionResult Index()
        {
            ViewBag.Categorias = new SelectList(_categoriaApp.GetAll(), "CategoriaId", "Nome");
            var receitaViewModel = Mapper.Map<IEnumerable<Receita>, IEnumerable<ReceitaViewModel>>(_receitaApp.GetAll());
            return View(receitaViewModel);
        }

        [HttpPost]
        public ViewResult Index(int? id)
        {
            ViewBag.Categorias = new SelectList(_categoriaApp.GetAll(), "CategoriaId", "Nome");
            var receitaViewModel = Mapper.Map<IEnumerable<Receita>, IEnumerable<ReceitaViewModel>>(id != null ? _categoriaApp.FiltrarReceitasPorCategoria(id) : _receitaApp.GetAll());
            return View(receitaViewModel);
        }

        //
        // GET: /Receitas/Details/5
        public ActionResult Details(int id)
        {
            var receita = _receitaApp.GetById(id);
            var receitaViewModel = Mapper.Map<Receita, ReceitaViewModel>(receita);
            return View(receitaViewModel);
        }

        //
        // GET: /Receitas/Create
        public ActionResult Create()
        {
            ViewBag.Categorias = new SelectList(_categoriaApp.GetAll(), "CategoriaId", "Nome");
            return View();
        }

        //
        // POST: /Receitas/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ReceitaViewModel receita)
        {
            if (ModelState.IsValid)
            {
                var receitaDomain = Mapper.Map<ReceitaViewModel, Receita>(receita);
                _receitaApp.Add(receitaDomain);
                return RedirectToAction("Index");
            }

            ViewBag.Categorias = new SelectList(_categoriaApp.GetAll(), "CategoriaId", "Nome", receita.CategoriaId);
            return View(receita);
        }

        //
        // GET: /Receitas/Edit/5
        public ActionResult Edit(int id)
        {
            var receita = _receitaApp.GetById(id);
            var receitaViewModel = Mapper.Map<Receita, ReceitaViewModel>(receita);
            ViewBag.Categorias = new SelectList(_categoriaApp.GetAll(), "CategoriaId", "Nome", receitaViewModel.CategoriaId);
            return View(receitaViewModel);
        }

        //
        // POST: /Receitas/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ReceitaViewModel receita)
        {
            if (ModelState.IsValid)
            {
                var receitaDomain = Mapper.Map<ReceitaViewModel, Receita>(receita);
                _receitaApp.Update(receitaDomain);
                return RedirectToAction("Index");
            }
            ViewBag.Categorias = new SelectList(_categoriaApp.GetAll(), "CategoriaId", "Nome", receita.CategoriaId);
            return View(receita);
        }

        //
        // GET: /Receitas/Delete/5
        public ActionResult Delete(int id)
        {
            var receita = _receitaApp.GetById(id);
            var receitaViewModel = Mapper.Map<Receita, ReceitaViewModel>(receita);
            return View(receitaViewModel);
        }

        //
        // POST: /Receitas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var receita = _receitaApp.GetById(id);
            _receitaApp.Remove(receita);
            return RedirectToAction("Index");
        }
    }
}

DesafioFortes.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Desafio Fortes</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Despesas", "Index", "Despesa")</li>
                    <li>@Html.ActionLink("Receitas", "Index", "Receita")</li>
                    <li>@Html.ActionLink("Relatórios", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Desafio Fortes</p>
        </footer>
    </div>
    <div class="modal" id="modal" tabindex="-1" role="dialog" aria-labelledby="ConfirmacaoDelete"></div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>